version: "3.9"
services:
  rumput:
    build: .
    container_name: rumput
    restart: unless-stopped
    ports:
      - "7500:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - RUMPUT_HOST=0.0.0.0
      - RUMPUT_PORT=3000
    volumes:
      - ./data-mount:/usr/src/app/data
      # - /usr/src/app/node_modules
